---

- hosts: all
  become: true
  tasks:

  - name: update and upgrade server
    apt:
        update_cache: true
        upgrade: dist
    when: ansible_distribution == "Ubuntu"



  - name: create user ansible
    user:
        name: ansible
        groups: root


  - name: add ssh key for user ansible
    authorized_keys:
        user: ansible
        key: "sh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILMnkp0wVuNi7UvddFM1Ru4mmOKy77pEczLA+wHebMnn ansible key"


  - name: add sudoers file for user ansible
    copy: 
        src: files/sudoers_ansible
        dest: /etc/sudoers.d/ansible
        owner: root
        group: root
        mode: 0440
