---

- hosts: linodeServers
  become: true
  tasks:

  - name: update repository index
    apt:
       update_cache: true

  - name: upgrade repository
    apt:
       upgrade: dist

  - name: install apache2 package
    apt:
       name: apache2
       state: latest
